# wrangler.toml - 安全配置模板
name = "email-forwarding-worker"
compatibility_date = "2024-05-01"
main = "worker.js"  # 指定入口文件
workers_dev = true  # 启用workers.dev域名

# 通过环境变量注入的配置（实际值不写在这里！）
[vars]
ZONE_ID = "${{ secrets.ZONE_ID }}"           # 从GitHub Secrets或.env注入
API_TOKEN = "${{ secrets.API_TOKEN }}"       # 从GitHub Secrets或.env注入
DOMAIN = "yourdomain.com"                    # 非敏感配置可保留

# KV命名空间配置（ID通过环境变量注入）
[[kv_namespaces]]
binding = "EMAIL_EXPIRY_KV"
id = "${{ secrets.KV_NAMESPACE_ID }}"        # 从GitHub Secrets或.env注入

# 定时触发器（可选）
[triggers]
crons = ["0 * * * *"]  # 每小时执行一次清理任务

