name = "email-forwarding-worker"
compatibility_date = "2024-05-01"
account_id = "YOUR_CF_ACCOUNT_ID"
workers_dev = true

[vars]
ZONE_ID = "your_zone_id"
API_TOKEN = "your_api_token"

# 正确写法：使用双括号表示数组
[[kv_namespaces]]
binding = "EMAIL_EXPIRY_KV"
id = "your_kv_namespace_id"
preview_id = "your_preview_id"  # 可选

[triggers]
crons = ["0 * * * *"]  # 每小时运行一次

